import { Coffee, Soup, Heart, BookOpen, AlarmClock, Trophy, Clapperboard, ChefHat, Music, Plane, Smartphone, UtensilsCrossed, ShoppingBag, Cake, Sparkles, Moon, type LucideIcon } from "lucide-react"

export interface Test {
  id: string
  title: string
  description: string
  icon: LucideIcon
  href: string
  color: string
  participants: string
  rating: number
  badge?: string
  category: string
  tags: string[]
  popular?: boolean
  new?: boolean
}

export const ALL_TESTS: Test[] = [
  {
    id: "coffee-mbti",
    title: "☕ 커피 MBTI",
    description: "당신의 커피 취향으로 알아보는 성격 유형",
    icon: Coffee,
    href: "/tests/coffee-mbti",
    color: "from-amber-500 to-orange-600",
    participants: "12.5K",
    rating: 4.8,
    badge: "HOT",
    category: "음식",
    tags: ["커피", "음료", "취향", "성격"],
    popular: true,
  },
  {
    id: "kdrama-mbti",
    title: "🎬 K-드라마 클리셰",
    description: "드라마 속 당신은 어떤 캐릭터?",
    icon: Clapperboard,
    href: "/tests/kdrama-mbti",
    color: "from-pink-500 to-purple-600",
    participants: "1.2K",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["드라마", "캐릭터", "K-드라마", "성격"],
    new: true,
  },
  {
    id: "snowwhite-mbti",
    title: "🍎 백설공주 에겐테토",
    description: "백설공주로 알아보는 에겐 vs 테토 성향",
    icon: Heart,
    href: "/tests/snowwhite-mbti",
    color: "from-pink-500 to-purple-600",
    participants: "3.2K",
    rating: 4.9,
    badge: "NEW",
    category: "동화",
    tags: ["백설공주", "에겐", "테토", "성격"],
    new: true,
  },
  {
    id: "ramen-mbti",
    title: "🍜 라면 MBTI",
    description: "라면 취향으로 알아보는 나의 성격",
    icon: Soup,
    href: "/tests/ramen-mbti",
    color: "from-red-500 to-pink-600",
    participants: "10.2K",
    rating: 4.7,
    category: "음식",
    tags: ["라면", "음식", "선택", "성격"],
    popular: true,
  },
  {
    id: "pet-mbti",
    title: "🐾 반려동물 MBTI",
    description: "반려동물 성향으로 알아보는 성격 테스트",
    icon: Heart,
    href: "/tests/pet-mbti",
    color: "from-pink-500 to-rose-600",
    participants: "8.9K",
    rating: 4.9,
    category: "관계",
    tags: ["반려동물", "관계", "성격", "동물"],
  },
  {
    id: "study-mbti",
    title: "📚 공부 MBTI",
    description: "나만의 공부 스타일 찾기",
    icon: BookOpen,
    href: "/tests/study-mbti",
    color: "from-blue-500 to-cyan-600",
    participants: "15.3K",
    rating: 4.6,
    category: "학습",
    tags: ["공부", "학습", "스타일", "성격"],
  },
  {
    id: "alarm-habit",
    title: "⏰ 알람 습관",
    description: "아침 알람으로 보는 성격 유형",
    icon: AlarmClock,
    href: "/tests/alarm-habit",
    color: "from-purple-500 to-indigo-600",
    participants: "7.8K",
    rating: 4.5,
    category: "생활",
    tags: ["알람", "습관", "생활", "패턴"],
  },
  {
    id: "ntrp-test",
    title: "🎾 NTRP 테스트",
    description: "테니스 실력 레벨 측정",
    icon: Trophy,
    href: "/tests/ntrp-test",
    color: "from-green-500 to-emerald-600",
    participants: "5.6K",
    rating: 4.7,
    category: "스포츠",
    tags: ["테니스", "스포츠", "실력", "레벨"],
  },
  {
    id: "kpop-idol",
    title: "🎤 K-팝 아이돌 포지션",
    description: "아이돌 그룹에서 내 포지션은?",
    icon: Trophy,
    href: "/tests/kpop-idol",
    color: "from-purple-500 to-pink-600",
    participants: "850",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["K-팝", "아이돌", "포지션", "성격"],
    new: true,
  },
  {
    id: "movie-theater-style",
    title: "🎬 영화관 관람 스타일",
    description: "영화관에서도 성격이 보인다고?",
    icon: Clapperboard,
    href: "/tests/movie-theater-style",
    color: "from-indigo-500 to-purple-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["영화관", "관람", "스타일", "성격"],
    new: true,
  },
  {
    id: "jachui",
    title: "🍳 자취 밥상 스타일",
    description: "오늘도 자취생의 밥상은 드라마다",
    icon: ChefHat,
    href: "/tests/jachui",
    color: "from-orange-500 to-amber-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["자취", "밥상", "요리", "성격"],
    new: true,
  },
  {
    id: "music-taste",
    title: "🎧 음악 취향 성격 테스트",
    description: "내 플레이리스트 속 성격, 당신은 어떤 음악 타입?",
    icon: Music,
    href: "/tests/music-taste",
    color: "from-purple-500 to-pink-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["음악", "플레이리스트", "음악 취향", "성격"],
    new: true,
  },
  {
    id: "cafe-style",
    title: "☕ 카페 스타일 성격 테스트",
    description: "카페에 가면 드러나는 당신의 성격",
    icon: Coffee,
    href: "/tests/cafe-style",
    color: "from-amber-500 to-brown-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["카페", "카공족", "커피", "카페 스타일", "성격"],
    new: true,
  },
  {
    id: "travel-style",
    title: "🧳 여행 짐 스타일 테스트",
    description: "여행 떠나기 전, 당신은 어떤 짐꾼인가요?",
    icon: Plane,
    href: "/tests/travel-style",
    color: "from-cyan-500 to-indigo-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["여행", "여행 짐", "여행 스타일", "짐 싸기", "성격"],
    new: true,
  },
  {
    id: "phone-style",
    title: "📱 스마트폰 사용 습관 테스트",
    description: "스마트폰 사용 습관으로 알아보는 나의 성격",
    icon: Smartphone,
    href: "/tests/phone-style",
    color: "from-violet-500 to-fuchsia-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["스마트폰", "휴대폰", "스마트폰 습관", "앱", "성격"],
    new: true,
  },
  {
    id: "phone-usage",
    title: "📱 스마트폰 사용 스타일",
    description: "알림, 앱 정리, 집중, 커뮤니케이션 습관으로 알아보는 나의 성향",
    icon: Smartphone,
    href: "/tests/phone-usage",
    color: "from-blue-500 to-indigo-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["스마트폰", "앱", "알림", "집중", "생산성"],
    new: true,
  },
  {
    id: "food-delivery",
    title: "🍕 배달 음식 선택 테스트",
    description: "배달 앱을 켜는 순간, 당신의 성격이 드러난다",
    icon: UtensilsCrossed,
    href: "/tests/food-delivery",
    color: "from-red-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["배달", "배달 음식", "음식 취향", "배달앱", "성격"],
    new: true,
  },
  {
    id: "shopping-style",
    title: "🛍️ 쇼핑 스타일 성격 테스트",
    description: "쇼핑할 때마다 드러나는 진짜 나의 성격",
    icon: ShoppingBag,
    href: "/tests/shopping-style",
    color: "from-pink-500 to-rose-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["쇼핑", "소비", "구매 스타일", "쇼핑 습관", "성격"],
    new: true,
  },
  {
    id: "dessert-style",
    title: "🍰 디저트 취향 성격 테스트",
    description: "디저트를 고르는 순간, 당신의 성격이 드러난다",
    icon: Cake,
    href: "/tests/dessert-style",
    color: "from-amber-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["디저트", "카페", "디저트 취향", "달콤한 취향", "성격"],
    new: true,
  },
  {
    id: "lunch-style",
    title: "🍱 회사 점심 뭐 먹지? 테스트",
    description: "회사 점심 선택에도 성격이 있다면?",
    icon: UtensilsCrossed,
    href: "/tests/lunch-style",
    color: "from-orange-500 to-red-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["점심", "회사 점심", "점심 메뉴", "오늘 뭐먹지", "점심 성격", "성격"],
    new: true,
  },
  {
    id: "clean-style",
    title: "🧹 방 청소 스타일 테스트",
    description: "청소하는 모습으로 알아보는 나의 성격!",
    icon: Sparkles,
    href: "/tests/clean-style",
    color: "from-blue-500 to-cyan-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["청소", "방 청소", "정리", "청소 습관", "방정리", "성격"],
    new: true,
  },
  {
    id: "evening-routine",
    title: "🌙 퇴근 후 루틴 테스트",
    description: "퇴근하고 집에 와서 하는 '그 행동들'에 당신의 성격이 숨어있습니다.",
    icon: Moon,
    href: "/tests/evening-routine",
    color: "from-purple-500 to-pink-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["퇴근 루틴", "저녁 루틴", "퇴근 후 뭐하지", "야근 후 회복", "저녁 습관", "성격"],
    new: true,
  },
  {
    id: "skin-routine",
    title: "✨ 피부 루틴 성향",
    description: "당신의 스킨케어 습관으로 알아보는 성향",
    icon: Sparkles,
    href: "/tests/skin-routine",
    color: "from-pink-500 to-rose-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "뷰티",
    tags: ["피부", "스킨케어", "루틴", "뷰티", "성향"],
    new: true,
  },
  {
    id: "spending-style",
    title: "💰 소비 성향 테스트",
    description: "계획성, 즉흥성, 비교 습관으로 알아보는 나의 소비 패턴",
    icon: ShoppingBag,
    href: "/tests/spending-style",
    color: "from-green-500 to-emerald-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["소비", "구매", "예산", "절약", "생산성"],
    new: true,
  },
  {
    id: "sleep-chronotype",
    title: "🌙 수면 크로노타입",
    description: "당신의 수면 리듬으로 알아보는 성향",
    icon: Moon,
    href: "/tests/sleep-chronotype",
    color: "from-indigo-500 to-purple-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["수면", "크로노타입", "리듬", "생활", "성향"],
    new: true,
  },
]

// Get all unique categories
export const CATEGORIES = ["전체", ...Array.from(new Set(ALL_TESTS.map((test) => test.category)))]

// Get tests for homepage (first 9, 중복 제거 후)
export const getHomePageTests = () => {
  const uniqueTests = getAllTests()
  return uniqueTests.slice(0, 9)
}

// Get all tests (중복 제거 및 정렬)
export const getAllTests = () => {
  // id 기준으로 중복 제거 (나중에 나온 항목 유지)
  const uniqueTests = new Map<string, Test>()
  for (const test of ALL_TESTS) {
    uniqueTests.set(test.id, test)
  }
  
  // id 기준으로 정렬하여 일관성 유지
  return Array.from(uniqueTests.values()).sort((a, b) => {
    // 먼저 id로 정렬
    if (a.id < b.id) return -1
    if (a.id > b.id) return 1
    return 0
  })
}
