import { Coffee, Soup, Heart, BookOpen, AlarmClock, Trophy, Clapperboard, ChefHat, Music, Plane, Smartphone, UtensilsCrossed, ShoppingBag, Cake, Sparkles, Moon, MessageSquare, Drumstick, Store, Play, Camera, Droplets, Gift, Salad, Bed, DoorOpen, Shirt, Thermometer, Cookie, Palette, Timer, Recycle, AlertTriangle, Flame, Candy, FileText, Snowflake, Sprout, Star, Lemon, type LucideIcon } from "lucide-react"

export interface Test {
  id: string
  title: string
  description: string
  icon: LucideIcon
  href: string
  color: string
  participants: string
  rating: number
  badge?: string
  category: string
  tags: string[]
  popular?: boolean
  new?: boolean
}

export const ALL_TESTS: Test[] = [
  {
    id: "coffee-mbti",
    title: "☕ 커피 MBTI",
    description: "당신의 커피 취향으로 알아보는 성격 유형",
    icon: Coffee,
    href: "/tests/coffee-mbti",
    color: "from-amber-500 to-orange-600",
    participants: "12.5K",
    rating: 4.8,
    badge: "HOT",
    category: "음식",
    tags: ["커피", "음료", "취향", "성격"],
    popular: true,
  },
  {
    id: "kdrama-mbti",
    title: "🎬 K-드라마 클리셰",
    description: "드라마 속 당신은 어떤 캐릭터?",
    icon: Clapperboard,
    href: "/tests/kdrama-mbti",
    color: "from-pink-500 to-purple-600",
    participants: "1.2K",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["드라마", "캐릭터", "K-드라마", "성격"],
    new: true,
  },
  {
    id: "snowwhite-mbti",
    title: "🍎 백설공주 에겐테토",
    description: "백설공주로 알아보는 에겐 vs 테토 성향",
    icon: Heart,
    href: "/tests/snowwhite-mbti",
    color: "from-pink-500 to-purple-600",
    participants: "3.2K",
    rating: 4.9,
    badge: "NEW",
    category: "동화",
    tags: ["백설공주", "에겐", "테토", "성격"],
    new: true,
  },
  {
    id: "ramen-mbti",
    title: "🍜 라면 MBTI",
    description: "라면 취향으로 알아보는 나의 성격",
    icon: Soup,
    href: "/tests/ramen-mbti",
    color: "from-red-500 to-pink-600",
    participants: "10.2K",
    rating: 4.7,
    category: "음식",
    tags: ["라면", "음식", "선택", "성격"],
    popular: true,
  },
  {
    id: "pet-mbti",
    title: "🐾 반려동물 MBTI",
    description: "반려동물 성향으로 알아보는 성격 테스트",
    icon: Heart,
    href: "/tests/pet-mbti",
    color: "from-pink-500 to-rose-600",
    participants: "8.9K",
    rating: 4.9,
    category: "관계",
    tags: ["반려동물", "관계", "성격", "동물"],
  },
  {
    id: "study-mbti",
    title: "📚 공부 MBTI",
    description: "나만의 공부 스타일 찾기",
    icon: BookOpen,
    href: "/tests/study-mbti",
    color: "from-blue-500 to-cyan-600",
    participants: "15.3K",
    rating: 4.6,
    category: "학습",
    tags: ["공부", "학습", "스타일", "성격"],
  },
  {
    id: "alarm-habit",
    title: "⏰ 알람 습관",
    description: "아침 알람으로 보는 성격 유형",
    icon: AlarmClock,
    href: "/tests/alarm-habit",
    color: "from-purple-500 to-indigo-600",
    participants: "7.8K",
    rating: 4.5,
    category: "생활",
    tags: ["알람", "습관", "생활", "패턴"],
  },
  {
    id: "ntrp-test",
    title: "🎾 NTRP 테스트",
    description: "테니스 실력 레벨 측정",
    icon: Trophy,
    href: "/tests/ntrp-test",
    color: "from-green-500 to-emerald-600",
    participants: "5.6K",
    rating: 4.7,
    category: "스포츠",
    tags: ["테니스", "스포츠", "실력", "레벨"],
  },
  {
    id: "kpop-idol",
    title: "🎤 K-팝 아이돌 포지션",
    description: "아이돌 그룹에서 내 포지션은?",
    icon: Trophy,
    href: "/tests/kpop-idol",
    color: "from-purple-500 to-pink-600",
    participants: "850",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["K-팝", "아이돌", "포지션", "성격"],
    new: true,
  },
  {
    id: "movie-theater-style",
    title: "🎬 영화관 관람 스타일",
    description: "영화관에서도 성격이 보인다고?",
    icon: Clapperboard,
    href: "/tests/movie-theater-style",
    color: "from-indigo-500 to-purple-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["영화관", "관람", "스타일", "성격"],
    new: true,
  },
  {
    id: "jachui",
    title: "🍳 자취 밥상 스타일",
    description: "오늘도 자취생의 밥상은 드라마다",
    icon: ChefHat,
    href: "/tests/jachui",
    color: "from-orange-500 to-amber-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["자취", "밥상", "요리", "성격"],
    new: true,
  },
  {
    id: "music-taste",
    title: "🎧 음악 취향 성격 테스트",
    description: "내 플레이리스트 속 성격, 당신은 어떤 음악 타입?",
    icon: Music,
    href: "/tests/music-taste",
    color: "from-purple-500 to-pink-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["음악", "플레이리스트", "음악 취향", "성격"],
    new: true,
  },
  {
    id: "cafe-style",
    title: "☕ 카페 스타일 성격 테스트",
    description: "카페에 가면 드러나는 당신의 성격",
    icon: Coffee,
    href: "/tests/cafe-style",
    color: "from-amber-500 to-brown-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["카페", "카공족", "커피", "카페 스타일", "성격"],
    new: true,
  },
  {
    id: "travel-style",
    title: "🧳 여행 짐 스타일 테스트",
    description: "여행 떠나기 전, 당신은 어떤 짐꾼인가요?",
    icon: Plane,
    href: "/tests/travel-style",
    color: "from-cyan-500 to-indigo-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["여행", "여행 짐", "여행 스타일", "짐 싸기", "성격"],
    new: true,
  },
  {
    id: "phone-style",
    title: "📱 스마트폰 사용 습관 테스트",
    description: "스마트폰 사용 습관으로 알아보는 나의 성격",
    icon: Smartphone,
    href: "/tests/phone-style",
    color: "from-violet-500 to-fuchsia-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["스마트폰", "휴대폰", "스마트폰 습관", "앱", "성격"],
    new: true,
  },
  {
    id: "phone-usage",
    title: "📱 스마트폰 사용 스타일",
    description: "알림, 앱 정리, 집중, 커뮤니케이션 습관으로 알아보는 나의 성향",
    icon: Smartphone,
    href: "/tests/phone-usage",
    color: "from-blue-500 to-indigo-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["스마트폰", "앱", "알림", "집중", "생산성"],
    new: true,
  },
  {
    id: "food-delivery",
    title: "🍕 배달 음식 선택 테스트",
    description: "배달 앱을 켜는 순간, 당신의 성격이 드러난다",
    icon: UtensilsCrossed,
    href: "/tests/food-delivery",
    color: "from-red-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["배달", "배달 음식", "음식 취향", "배달앱", "성격"],
    new: true,
  },
  {
    id: "shopping-style",
    title: "🛍️ 쇼핑 스타일 성격 테스트",
    description: "쇼핑할 때마다 드러나는 진짜 나의 성격",
    icon: ShoppingBag,
    href: "/tests/shopping-style",
    color: "from-pink-500 to-rose-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["쇼핑", "소비", "구매 스타일", "쇼핑 습관", "성격"],
    new: true,
  },
  {
    id: "dessert-style",
    title: "🍰 디저트 취향 성격 테스트",
    description: "디저트를 고르는 순간, 당신의 성격이 드러난다",
    icon: Cake,
    href: "/tests/dessert-style",
    color: "from-amber-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["디저트", "카페", "디저트 취향", "달콤한 취향", "성격"],
    new: true,
  },
  {
    id: "clean-style",
    title: "🧹 방 청소 스타일 테스트",
    description: "청소하는 모습으로 알아보는 나의 성격!",
    icon: Sparkles,
    href: "/tests/clean-style",
    color: "from-blue-500 to-cyan-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["청소", "방 청소", "정리", "청소 습관", "방정리", "성격"],
    new: true,
  },
  {
    id: "evening-routine",
    title: "🌙 퇴근 후 루틴 테스트",
    description: "퇴근하고 집에 와서 하는 '그 행동들'에 당신의 성격이 숨어있습니다.",
    icon: Moon,
    href: "/tests/evening-routine",
    color: "from-purple-500 to-pink-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["퇴근 루틴", "저녁 루틴", "퇴근 후 뭐하지", "야근 후 회복", "저녁 습관", "성격"],
    new: true,
  },
  {
    id: "skin-routine",
    title: "✨ 피부 루틴 성향",
    description: "당신의 스킨케어 습관으로 알아보는 성향",
    icon: Sparkles,
    href: "/tests/skin-routine",
    color: "from-pink-500 to-rose-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "뷰티",
    tags: ["피부", "스킨케어", "루틴", "뷰티", "성향"],
    new: true,
  },
  {
    id: "spending-style",
    title: "💰 소비 성향 테스트",
    description: "계획성, 즉흥성, 비교 습관으로 알아보는 나의 소비 패턴",
    icon: ShoppingBag,
    href: "/tests/spending-style",
    color: "from-green-500 to-emerald-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["소비", "구매", "예산", "절약", "생산성"],
    new: true,
  },
  {
    id: "sleep-chronotype",
    title: "🌙 수면 크로노타입",
    description: "당신의 수면 리듬으로 알아보는 성향",
    icon: Moon,
    href: "/tests/sleep-chronotype",
    color: "from-indigo-500 to-purple-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["수면", "크로노타입", "리듬", "생활", "성향"],
    new: true,
  },
  {
    id: "chicken-style",
    title: "🍗 치킨 주문 스타일 테스트",
    description: "치킨 주문 습관으로 16유형 성향을 분석합니다",
    icon: Drumstick,
    href: "/tests/chicken-style",
    color: "from-yellow-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["치킨", "치킨 성향", "치킨 반반", "치킨 주문", "배달 음식", "성격"],
    new: true,
  },
  {
    id: "convenience-snack",
    title: "🏪 편의점 간식 루틴 테스트",
    description: "편의점 간식 선택 루틴으로 성향을 분석합니다",
    icon: Store,
    href: "/tests/convenience-snack",
    color: "from-green-500 to-emerald-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["편의점", "간식", "편의점 루틴", "신상품", "행사", "성향"],
    new: true,
  },
  {
    id: "cstore-routine",
    title: "🏬 편의점 루틴 테스트",
    description: "편의점 선택 습관으로 보는 16유형",
    icon: Store,
    href: "/tests/cstore-routine",
    color: "from-blue-500 to-cyan-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["편의점", "편의점 루틴", "간편식", "원플러스원", "장바구니", "성향"],
    new: true,
  },
  {
    id: "cvs-combo",
    title: "🛒 편의점 조합 스타일 테스트",
    description: "편의점 선택 습관으로 16유형 성향을 분석합니다",
    icon: ShoppingBag,
    href: "/tests/cvs-combo",
    color: "from-green-500 to-teal-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["편의점", "편의점 조합", "야식", "간편식", "편의점 루틴", "성향"],
    new: true,
  },
  {
    id: "kakao-reply-style",
    title: "💬 카톡 답장 스타일 테스트",
    description: "답장 속도·말투·읽씹 습관으로 보는 소통 성향",
    icon: MessageSquare,
    href: "/tests/kakao-reply-style",
    color: "from-yellow-400 to-orange-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["카톡", "답장 스타일", "메신저", "소통", "읽씹", "성격"],
    new: true,
  },
  {
    id: "love-texting-style",
    title: "💕 연애 연락 텐션 테스트",
    description: "연락 속도·길이·톤으로 보는 연애 커뮤니케이션 유형",
    icon: Heart,
    href: "/tests/love-texting-style",
    color: "from-pink-500 to-rose-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "관계",
    tags: ["연애", "연락", "썸", "연애 텐션", "커뮤니케이션", "성격"],
    new: true,
  },
  {
    id: "lunch-decider",
    title: "🍱 회사 점심 뭐 먹지 테스트",
    description: "직장인 점심 의사결정 스타일을 분석합니다",
    icon: UtensilsCrossed,
    href: "/tests/lunch-decider",
    color: "from-amber-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["회사 점심", "점심 메뉴", "직장인", "점심 결정", "팀밥", "혼밥", "성격"],
    new: true,
  },
  {
    id: "youtube-habit",
    title: "📺 유튜브 시청 습관 테스트",
    description: "유튜브 시청 습관으로 16유형 성향을 분석합니다",
    icon: Play,
    href: "/tests/youtube-habit",
    color: "from-red-500 to-pink-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["유튜브", "시청 습관", "영상 배속", "플레이리스트", "유튜브 유형", "성격"],
    new: true,
  },
  {
    id: "love-reaction",
    title: "💕 연애 상황 반응 테스트",
    description: "연락 습관, 갈등 해결, 데이트 운영, 감정 표현으로 16유형 분석",
    icon: Heart,
    href: "/tests/love-reaction",
    color: "from-pink-500 to-rose-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "관계",
    tags: ["연애", "연락", "데이트", "갈등 해결", "감정 표현", "성격"],
    new: true,
  },
  {
    id: "ott-habits",
    title: "📺 OTT 시청 습관 테스트",
    description: "정주행 방식, 추천 활용, 스포 대처, 감상 기록 습관으로 16유형 분석",
    icon: Play,
    href: "/tests/ott-habits",
    color: "from-purple-500 to-indigo-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["OTT", "시청 습관", "정주행", "추천 알고리즘", "스포일러", "성격"],
    new: true,
  },
  {
    id: "bungeoppang",
    title: "🐟 붕어빵 취향 테스트",
    description: "맛 선택, 구매 방식, 먹는 습관으로 16유형 분석",
    icon: Cake,
    href: "/tests/bungeoppang",
    color: "from-orange-500 to-red-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["붕어빵", "겨울 간식", "팥 슈크림", "길거리 간식", "성향 테스트", "성격"],
    new: true,
  },
  {
    id: "kdrama-character",
    title: "🎬 K-드라마 인물 매칭 테스트",
    description: "드라마 속 상황 선택으로 내 캐릭터 유형 찾기",
    icon: Clapperboard,
    href: "/tests/kdrama-character",
    color: "from-pink-500 to-purple-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["K드라마", "캐릭터 테스트", "인물 매칭", "드라마 캐릭터", "성격 테스트"],
    new: true,
  },
  {
    id: "hamburger-combo",
    title: "🍔 햄버거 조합 스타일 테스트",
    description: "패티, 빵, 야채, 소스 선택으로 알아보는 나의 성격",
    icon: UtensilsCrossed,
    href: "/tests/hamburger-combo",
    color: "from-orange-500 to-red-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["햄버거", "패티", "빵", "소스", "조합", "성격"],
    new: true,
  },
  {
    id: "pizza-topping",
    title: "🍕 피자 토핑 선택 테스트",
    description: "토핑 선택 습관으로 알아보는 나의 성격",
    icon: UtensilsCrossed,
    href: "/tests/pizza-topping",
    color: "from-red-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["피자", "토핑", "페퍼로니", "치즈", "성격"],
    new: true,
  },
  {
    id: "instagram-story",
    title: "📸 인스타그램 스토리 스타일 테스트",
    description: "스토리 올리는 방식으로 알아보는 나의 성격",
    icon: Camera,
    href: "/tests/instagram-story",
    color: "from-pink-500 to-purple-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["인스타그램", "스토리", "SNS", "필터", "성격"],
    new: true,
  },
  {
    id: "shower-habit",
    title: "🚿 샤워 습관 테스트",
    description: "샤워 시간, 순서, 온도로 알아보는 나의 성격",
    icon: Droplets,
    href: "/tests/shower-habit",
    color: "from-blue-500 to-cyan-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["샤워", "습관", "루틴", "일상", "성격"],
    new: true,
  },
  {
    id: "gift-wrapping",
    title: "🎁 포장지 뜯는 스타일 테스트",
    description: "포장지 뜯는 방식으로 알아보는 나의 성격",
    icon: Gift,
    href: "/tests/gift-wrapping",
    color: "from-yellow-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["포장지", "선물", "뜯기", "습관", "성격"],
    new: true,
  },
  {
    id: "karaoke-song",
    title: "🎤 노래방 곡 선택 테스트",
    description: "노래방 곡 선택 방식으로 알아보는 나의 성격",
    icon: Music,
    href: "/tests/karaoke-song",
    color: "from-pink-500 to-red-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["노래방", "곡 선택", "노래", "음악", "성격"],
    new: true,
  },
  {
    id: "soup-vs-bibim",
    title: "🍜 국물 vs 비빔 스타일 테스트",
    description: "국물파 vs 비빔파로 알아보는 나의 성격",
    icon: UtensilsCrossed,
    href: "/tests/soup-vs-bibim",
    color: "from-blue-500 to-green-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["국물", "비빔", "국물파", "비빔파", "성격"],
    new: true,
  },
  {
    id: "lunchbox-style",
    title: "🍱 도시락 싸는 스타일 테스트",
    description: "도시락 구성, 포장으로 알아보는 나의 성격",
    icon: UtensilsCrossed,
    href: "/tests/lunchbox-style",
    color: "from-amber-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["도시락", "포장", "구성", "정리", "성격"],
    new: true,
  },
  {
    id: "game-play-style",
    title: "🎮 게임 플레이 스타일 테스트",
    description: "게임 플레이 방식으로 알아보는 나의 성격",
    icon: Play,
    href: "/tests/game-play-style",
    color: "from-purple-500 to-indigo-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "엔터테인먼트",
    tags: ["게임", "플레이", "게이머", "스타일", "성격"],
    new: true,
  },
  {
    id: "gift-choosing",
    title: "💝 선물 고르는 스타일 테스트",
    description: "선물 선택 기준, 포장 방식으로 알아보는 나의 성격",
    icon: Gift,
    href: "/tests/gift-choosing",
    color: "from-pink-500 to-rose-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "관계",
    tags: ["선물", "선택", "포장", "배려", "성격"],
    new: true,
  },
  {
    id: "chicken-vs-jjimdak",
    title: "🍗 찜닭 vs 치킨 선택 테스트",
    description: "찜닭파 vs 치킨파로 알아보는 나의 성격",
    icon: UtensilsCrossed,
    href: "/tests/chicken-vs-jjimdak",
    color: "from-orange-500 to-red-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["찜닭", "치킨", "찜닭파", "치킨파", "성격"],
    new: true,
  },
  {
    id: "cake-cutting",
    title: "🍰 케이크 자르는 스타일 테스트",
    description: "케이크 자르는 방식, 조각 선택으로 알아보는 나의 성격",
    icon: Cake,
    href: "/tests/cake-cutting",
    color: "from-pink-500 to-rose-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["케이크", "자르기", "조각", "배분", "성격"],
    new: true,
  },
  {
    id: "kimbap-ingredient",
    title: "🍙 김밥 재료 선택 테스트",
    description: "김밥 재료 선택으로 알아보는 나의 성격",
    icon: UtensilsCrossed,
    href: "/tests/kimbap-ingredient",
    color: "from-green-500 to-emerald-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["김밥", "재료", "선택", "조합", "성격"],
    new: true,
  },
  {
    id: "stew-vs-soup",
    title: "🍲 찌개 vs 국물 스타일 테스트",
    description: "찌개 종류 선택, 국물 마시는 습관으로 알아보는 나의 성격",
    icon: Soup,
    href: "/tests/stew-vs-soup",
    color: "from-orange-500 to-red-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["찌개", "국물", "된장찌개", "김치찌개", "성격"],
    new: true,
  },
  {
    id: "salad-dressing",
    title: "🥗 샐러드 드레싱 선택 테스트",
    description: "샐러드 드레싱 선택으로 알아보는 나의 성격",
    icon: Salad,
    href: "/tests/salad-dressing",
    color: "from-green-500 to-lime-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["샐러드", "드레싱", "올리브오일", "발사믹", "성격"],
    new: true,
  },
  {
    id: "meat-grilling",
    title: "🍖 고기 굽는 스타일 테스트",
    description: "고기 굽는 방식, 익힘 정도 선호로 알아보는 나의 성격",
    icon: Drumstick,
    href: "/tests/meat-grilling",
    color: "from-red-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["고기", "굽기", "레어", "웰던", "성격"],
    new: true,
  },
  {
    id: "bed-making",
    title: "🛏️ 침대 정리 스타일 테스트",
    description: "침대 정리 습관, 베개 배치로 알아보는 나의 성격",
    icon: Bed,
    href: "/tests/bed-making",
    color: "from-blue-500 to-indigo-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["침대", "정리", "베개", "배치", "성격"],
    new: true,
  },
  {
    id: "door-closing",
    title: "🚪 문 닫는 스타일 테스트",
    description: "문 닫는 방식, 잠금 습관으로 알아보는 나의 성격",
    icon: DoorOpen,
    href: "/tests/door-closing",
    color: "from-purple-500 to-pink-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["문", "닫기", "잠금", "습관", "성격"],
    new: true,
  },
  {
    id: "bathroom-habit",
    title: "🚿 화장실 사용 습관 테스트",
    description: "화장실 사용 패턴, 정리 습관으로 알아보는 나의 성격",
    icon: Droplets,
    href: "/tests/bathroom-habit",
    color: "from-cyan-500 to-blue-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["화장실", "사용", "정리", "습관", "성격"],
    new: true,
  },
  {
    id: "sock-wearing",
    title: "🧦 양말 신는 스타일 테스트",
    description: "양말 선택, 신는 방식으로 알아보는 나의 성격",
    icon: Shirt,
    href: "/tests/sock-wearing",
    color: "from-yellow-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["양말", "선택", "신기", "매칭", "성격"],
    new: true,
  },
  {
    id: "clothing-order",
    title: "👔 옷 입는 순서 테스트",
    description: "옷 입는 순서, 스타일로 알아보는 나의 성격",
    icon: Shirt,
    href: "/tests/clothing-order",
    color: "from-indigo-500 to-purple-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["옷", "입기", "순서", "조합", "성격"],
    new: true,
  },
  {
    id: "subway-vs-bus",
    title: "🚇 지하철 vs 버스 선택 테스트",
    description: "지하철 vs 버스 선택 기준으로 알아보는 나의 성격",
    icon: Plane,
    href: "/tests/subway-vs-bus",
    color: "from-sky-500 to-blue-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["지하철", "버스", "대중교통", "선택", "성격"],
    new: true,
  },
  {
    id: "bag-organizing",
    title: "🎒 가방 정리 스타일 테스트",
    description: "가방 정리 방식, 스타일로 알아보는 나의 성격",
    icon: ShoppingBag,
    href: "/tests/bag-organizing",
    color: "from-amber-500 to-orange-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["가방", "정리", "스타일", "조합", "성격"],
    new: true,
  },
  {
    id: "laundry-habit",
    title: "🧺 세탁 습관 테스트",
    description: "세탁 방식, 습관으로 알아보는 나의 성격",
    icon: Droplets,
    href: "/tests/laundry-habit",
    color: "from-cyan-500 to-blue-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["세탁", "습관", "방식", "정리", "성격"],
    new: true,
  },
  {
    id: "chair-sitting",
    title: "🪑 의자 앉는 스타일 테스트",
    description: "의자 앉는 방식, 스타일로 알아보는 나의 성격",
    icon: Bed,
    href: "/tests/chair-sitting",
    color: "from-emerald-500 to-teal-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["의자", "앉기", "스타일", "자세", "성격"],
    new: true,
  },
  {
    id: "water-drinking",
    title: "💧 물 마시는 습관 테스트",
    description: "물 마시는 방식, 습관으로 알아보는 나의 성격",
    icon: Droplets,
    href: "/tests/water-drinking",
    color: "from-blue-500 to-cyan-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["물", "마시기", "습관", "방식", "성격"],
    new: true,
  },
  {
    id: "mirror-habit",
    title: "🪞 거울 보는 습관 테스트",
    description: "거울 보는 방식, 습관으로 알아보는 나의 성격",
    icon: Camera,
    href: "/tests/mirror-habit",
    color: "from-rose-500 to-pink-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["거울", "보기", "습관", "방식", "성격"],
    new: true,
  },
  {
    id: "book-reading",
    title: "📚 책 읽는 습관 테스트",
    description: "책 읽는 방식, 습관으로 알아보는 나의 성격",
    icon: BookOpen,
    href: "/tests/book-reading",
    color: "from-violet-500 to-purple-600",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "생활",
    tags: ["책", "읽기", "습관", "방식", "성격"],
    new: true,
  },
  {
    id: "food-temperature",
    title: "🌡️ 음식 온도 선호도 테스트",
    description: "뜨거운 음식 vs 차가운 음식 선호로 16유형 성향을 분석합니다",
    icon: Thermometer,
    href: "/tests/food-temperature",
    color: "from-red-500 to-blue-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["음식 온도", "선호도", "식습관"],
    new: true,
  },
  {
    id: "food-texture",
    title: "🍮 음식 질감 선호도 테스트",
    description: "부드러운 vs 쫄깃한 질감 선호로 16유형 성향을 분석합니다",
    icon: Cookie,
    href: "/tests/food-texture",
    color: "from-purple-500 to-pink-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["음식 질감", "식감", "선호도"],
    new: true,
  },
  {
    id: "food-presentation",
    title: "🎨 음식 플레이팅 선호도 테스트",
    description: "음식 모양과 배치 선호로 16유형 성향을 분석합니다",
    icon: Palette,
    href: "/tests/food-presentation",
    color: "from-indigo-500 to-purple-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["플레이팅", "음식 예술", "시각적"],
    new: true,
  },
  {
    id: "food-combination",
    title: "🍱 음식 조합 스타일 테스트",
    description: "음식 섞어 먹기 vs 따로 먹기로 16유형 성향을 분석합니다",
    icon: UtensilsCrossed,
    href: "/tests/food-combination",
    color: "from-teal-500 to-cyan-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["음식 조합", "섞어 먹기", "식습관"],
    new: true,
  },
  {
    id: "food-timing",
    title: "⏰ 식사 시간대 테스트",
    description: "식사 시간대와 규칙성으로 16유형 성향을 분석합니다",
    icon: Timer,
    href: "/tests/food-timing",
    color: "from-orange-500 to-red-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["식사 시간", "시간대", "규칙성"],
    new: true,
  },
  {
    id: "food-waste",
    title: "♻️ 음식 낭비 대처 테스트",
    description: "음식 남기고 버리는 방식으로 16유형 성향을 분석합니다",
    icon: Recycle,
    href: "/tests/food-waste",
    color: "from-green-500 to-emerald-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["음식 낭비", "절약", "환경"],
    new: true,
  },
  {
    id: "food-allergy",
    title: "⚠️ 알레르기 대처 스타일 테스트",
    description: "알레르기 음식 피하는 방식으로 16유형 성향을 분석합니다",
    icon: AlertTriangle,
    href: "/tests/food-allergy",
    color: "from-yellow-500 to-orange-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["알레르기", "건강", "주의"],
    new: true,
  },
  {
    id: "food-spiciness",
    title: "🌶️ 매운맛 선호도 테스트",
    description: "매운맛을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Flame,
    href: "/tests/food-spiciness",
    color: "from-red-500 to-orange-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["매운맛", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-sweetness",
    title: "🍬 단맛 선호도 테스트",
    description: "단맛을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Candy,
    href: "/tests/food-sweetness",
    color: "from-pink-500 to-purple-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["단맛", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-sourness",
    title: "🍋 신맛 선호도 테스트",
    description: "신맛을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Lemon,
    href: "/tests/food-sourness",
    color: "from-yellow-500 to-orange-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["신맛", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-saltiness",
    title: "🧂 짠맛 선호도 테스트",
    description: "짠맛을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: UtensilsCrossed,
    href: "/tests/food-saltiness",
    color: "from-blue-500 to-teal-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["짠맛", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-bitterness",
    title: "☕ 쓴맛 선호도 테스트",
    description: "쓴맛을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Coffee,
    href: "/tests/food-bitterness",
    color: "from-amber-500 to-brown-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["쓴맛", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-umami",
    title: "🍖 감칠맛 선호도 테스트",
    description: "감칠맛을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Drumstick,
    href: "/tests/food-umami",
    color: "from-red-500 to-orange-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["감칠맛", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-crispy",
    title: "🍪 바삭함 선호도 테스트",
    description: "바삭함을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Cookie,
    href: "/tests/food-crispy",
    color: "from-yellow-500 to-orange-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["바삭함", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-chewy",
    title: "💗 쫄깃함 선호도 테스트",
    description: "쫄깃함을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Heart,
    href: "/tests/food-chewy",
    color: "from-pink-500 to-red-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["쫄깃함", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-creamy",
    title: "🍰 부드러움 선호도 테스트",
    description: "부드러움을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Cake,
    href: "/tests/food-creamy",
    color: "from-purple-500 to-pink-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["부드러움", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-crunchy",
    title: "🥗 아삭함 선호도 테스트",
    description: "아삭함을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Salad,
    href: "/tests/food-crunchy",
    color: "from-green-500 to-teal-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["아삭함", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-portion",
    title: "🍽️ 음식 양 선호도 테스트",
    description: "음식 양을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: UtensilsCrossed,
    href: "/tests/food-portion",
    color: "from-indigo-500 to-purple-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["음식 양", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-plating",
    title: "🎨 음식 접시 배치 스타일 테스트",
    description: "음식 접시 배치 방식을 통해 알아보는 나의 성격 유형",
    icon: Palette,
    href: "/tests/food-plating",
    color: "from-violet-500 to-fuchsia-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["접시 배치", "플레이팅", "음식 스타일"],
    new: true,
  },
  {
    id: "food-garnishing-style",
    title: "🌿 음식 장식 선호도 테스트",
    description: "음식 장식을 좋아하는 정도와 방식으로 알아보는 나의 성격 유형",
    icon: Sprout,
    href: "/tests/food-garnishing-style",
    color: "from-emerald-500 to-teal-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["음식 장식", "선호도", "음식 취향"],
    new: true,
  },
  {
    id: "food-label",
    title: "🏷️ 식품 라벨 확인 스타일 테스트",
    description: "식품 라벨 읽는 습관으로 16유형 성향을 분석합니다",
    icon: FileText,
    href: "/tests/food-label",
    color: "from-blue-500 to-cyan-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["식품 라벨", "건강", "정보 확인"],
    new: true,
  },
  {
    id: "food-storage",
    title: "❄️ 음식 보관 스타일 테스트",
    description: "냉장고 정리와 보관 방식으로 16유형 성향을 분석합니다",
    icon: Snowflake,
    href: "/tests/food-storage",
    color: "from-cyan-500 to-blue-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["음식 보관", "냉장고", "정리"],
    new: true,
  },
  {
    id: "food-reheating",
    title: "🔥 음식 재가열 스타일 테스트",
    description: "남은 음식 데우는 방식으로 16유형 성향을 분석합니다",
    icon: Flame,
    href: "/tests/food-reheating",
    color: "from-orange-500 to-red-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["재가열", "전자레인지", "데우기"],
    new: true,
  },
  {
    id: "food-seasoning",
    title: "🧂 양념 사용 스타일 테스트",
    description: "양념 사용량과 방식으로 16유형 성향을 분석합니다",
    icon: ChefHat,
    href: "/tests/food-seasoning",
    color: "from-amber-500 to-yellow-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["양념", "조미료", "취향"],
    new: true,
  },
  {
    id: "food-garnishing",
    title: "🌿 음식 장식 스타일 테스트",
    description: "음식 꾸미기와 장식 선호로 16유형 성향을 분석합니다",
    icon: Sprout,
    href: "/tests/food-garnishing",
    color: "from-green-500 to-emerald-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["장식", "플레이팅", "미식"],
    new: true,
  },
  {
    id: "food-ordering",
    title: "📱 주문 방식 테스트",
    description: "직접 주문 vs 앱 주문 선호로 16유형 성향을 분석합니다",
    icon: Smartphone,
    href: "/tests/food-ordering",
    color: "from-indigo-500 to-purple-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["주문", "앱 주문", "주문 방식"],
    new: true,
  },
  {
    id: "food-review",
    title: "⭐ 음식 리뷰 작성 스타일 테스트",
    description: "음식 리뷰 쓰는 방식으로 16유형 성향을 분석합니다",
    icon: Star,
    href: "/tests/food-review",
    color: "from-yellow-500 to-orange-500",
    participants: "0",
    rating: 5.0,
    badge: "NEW",
    category: "음식",
    tags: ["리뷰", "평가", "공유"],
    new: true,
  },
]

// Get all unique categories
export const CATEGORIES = ["전체", ...Array.from(new Set(ALL_TESTS.map((test) => test.category)))]

// Get tests for homepage (first 9, 중복 제거 후)
export const getHomePageTests = () => {
  const uniqueTests = getAllTests()
  return uniqueTests.slice(0, 9)
}

// Get all tests (중복 제거 및 정렬)
export const getAllTests = () => {
  // id 기준으로 중복 제거 (나중에 나온 항목 유지)
  const uniqueTests = new Map<string, Test>()
  for (const test of ALL_TESTS) {
    uniqueTests.set(test.id, test)
  }
  
  // id 기준으로 정렬하여 일관성 유지
  return Array.from(uniqueTests.values()).sort((a, b) => {
    // 먼저 id로 정렬
    if (a.id < b.id) return -1
    if (a.id > b.id) return 1
    return 0
  })
}
