/**
 * 퀴즈 색상 스키마 유틸리티
 * 각 퀴즈별 색상 클래스를 정의
 */

import type { QuizColorClasses } from "@/components/quiz/quiz-container"

export const quizColorSchemes: Record<string, QuizColorClasses> = {
  "blue-green": {
    selectedBorder: "border-blue-500",
    selectedBg: "bg-gradient-to-r from-blue-50 to-green-50 dark:from-blue-950 dark:to-green-950",
    hoverBorder: "hover:border-blue-300 dark:hover:border-blue-600",
    hoverBg: "hover:bg-blue-50/50 dark:hover:bg-blue-950/50",
    focusRing: "focus-visible:ring-blue-500",
    radioSelected: "border-blue-500 bg-blue-500",
    questionNumberBg: "bg-gradient-to-br from-blue-400 to-green-500",
  },
  "blue-purple": {
    selectedBorder: "border-blue-500",
    selectedBg: "bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-950 dark:to-purple-950",
    hoverBorder: "hover:border-blue-300 dark:hover:border-blue-600",
    hoverBg: "hover:bg-blue-50/50 dark:hover:bg-blue-950/50",
    focusRing: "focus-visible:ring-blue-500",
    radioSelected: "border-blue-500 bg-blue-500",
    questionNumberBg: "bg-gradient-to-br from-blue-400 to-purple-500",
  },
  "orange-red": {
    selectedBorder: "border-orange-500",
    selectedBg: "bg-gradient-to-r from-orange-50 to-red-50 dark:from-orange-950 dark:to-red-950",
    hoverBorder: "hover:border-orange-300 dark:hover:border-orange-600",
    hoverBg: "hover:bg-orange-50/50 dark:hover:bg-orange-950/50",
    focusRing: "focus-visible:ring-orange-500",
    radioSelected: "border-orange-500 bg-orange-500",
    questionNumberBg: "bg-gradient-to-br from-orange-400 to-red-500",
  },
  "yellow-orange": {
    selectedBorder: "border-yellow-500",
    selectedBg: "bg-gradient-to-r from-yellow-50 to-orange-50 dark:from-yellow-950 dark:to-orange-950",
    hoverBorder: "hover:border-yellow-300 dark:hover:border-yellow-600",
    hoverBg: "hover:bg-yellow-50/50 dark:hover:bg-yellow-950/50",
    focusRing: "focus-visible:ring-yellow-500",
    radioSelected: "border-yellow-500 bg-yellow-500",
    questionNumberBg: "bg-gradient-to-br from-yellow-400 to-orange-500",
  },
  "green-emerald": {
    selectedBorder: "border-green-500",
    selectedBg: "bg-gradient-to-r from-green-50 to-emerald-50 dark:from-green-950 dark:to-emerald-950",
    hoverBorder: "hover:border-green-300 dark:hover:border-green-600",
    hoverBg: "hover:bg-green-50/50 dark:hover:bg-green-950/50",
    focusRing: "focus-visible:ring-green-500",
    radioSelected: "border-green-500 bg-green-500",
    questionNumberBg: "bg-gradient-to-br from-green-400 to-emerald-500",
  },
  "blue-indigo": {
    selectedBorder: "border-blue-500",
    selectedBg: "bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-950 dark:to-indigo-950",
    hoverBorder: "hover:border-blue-300 dark:hover:border-blue-600",
    hoverBg: "hover:bg-blue-50/50 dark:hover:bg-blue-950/50",
    focusRing: "focus-visible:ring-blue-500",
    radioSelected: "border-blue-500 bg-blue-500",
    questionNumberBg: "bg-gradient-to-br from-blue-400 to-indigo-500",
  },
  "amber-yellow": {
    selectedBorder: "border-amber-500",
    selectedBg: "bg-gradient-to-r from-amber-50 to-yellow-50 dark:from-amber-950 dark:to-yellow-950",
    hoverBorder: "hover:border-amber-300 dark:hover:border-amber-600",
    hoverBg: "hover:bg-amber-50/50 dark:hover:bg-amber-950/50",
    focusRing: "focus-visible:ring-amber-500",
    radioSelected: "border-amber-500 bg-amber-500",
    questionNumberBg: "bg-gradient-to-br from-amber-400 to-yellow-500",
  },
  "blue-cyan": {
    selectedBorder: "border-blue-500",
    selectedBg: "bg-gradient-to-r from-blue-50 to-cyan-50 dark:from-blue-950 dark:to-cyan-950",
    hoverBorder: "hover:border-blue-300 dark:hover:border-blue-600",
    hoverBg: "hover:bg-blue-50/50 dark:hover:bg-blue-950/50",
    focusRing: "focus-visible:ring-blue-500",
    radioSelected: "border-blue-500 bg-blue-500",
    questionNumberBg: "bg-gradient-to-br from-blue-400 to-cyan-500",
  },
  "blue-teal": {
    selectedBorder: "border-blue-500",
    selectedBg: "bg-gradient-to-r from-blue-50 to-teal-50 dark:from-blue-950 dark:to-teal-950",
    hoverBorder: "hover:border-blue-300 dark:hover:border-blue-600",
    hoverBg: "hover:bg-blue-50/50 dark:hover:bg-blue-950/50",
    focusRing: "focus-visible:ring-blue-500",
    radioSelected: "border-blue-500 bg-blue-500",
    questionNumberBg: "bg-gradient-to-br from-blue-400 to-teal-500",
  },
  "green-blue": {
    selectedBorder: "border-green-500",
    selectedBg: "bg-gradient-to-r from-green-50 to-blue-50 dark:from-green-950 dark:to-blue-950",
    hoverBorder: "hover:border-green-300 dark:hover:border-green-600",
    hoverBg: "hover:bg-green-50/50 dark:hover:bg-green-950/50",
    focusRing: "focus-visible:ring-green-500",
    radioSelected: "border-green-500 bg-green-500",
    questionNumberBg: "bg-gradient-to-br from-green-400 to-blue-500",
  },
  "pink-rose": {
    selectedBorder: "border-pink-500",
    selectedBg: "bg-gradient-to-r from-pink-50 to-rose-50 dark:from-pink-950 dark:to-rose-950",
    hoverBorder: "hover:border-pink-300 dark:hover:border-pink-600",
    hoverBg: "hover:bg-pink-50/50 dark:hover:bg-pink-950/50",
    focusRing: "focus-visible:ring-pink-500",
    radioSelected: "border-pink-500 bg-pink-500",
    questionNumberBg: "bg-gradient-to-br from-pink-400 to-rose-500",
  },
  "purple-pink": {
    selectedBorder: "border-purple-500",
    selectedBg: "bg-gradient-to-r from-purple-50 to-pink-50 dark:from-purple-950 dark:to-pink-950",
    hoverBorder: "hover:border-purple-300 dark:hover:border-purple-600",
    hoverBg: "hover:bg-purple-50/50 dark:hover:bg-purple-950/50",
    focusRing: "focus-visible:ring-purple-500",
    radioSelected: "border-purple-500 bg-purple-500",
    questionNumberBg: "bg-gradient-to-br from-purple-400 to-pink-500",
  },
  "fuchsia-rose": {
    selectedBorder: "border-fuchsia-500",
    selectedBg: "bg-gradient-to-r from-fuchsia-50 to-rose-50 dark:from-fuchsia-950 dark:to-rose-950",
    hoverBorder: "hover:border-fuchsia-300 dark:hover:border-fuchsia-600",
    hoverBg: "hover:bg-fuchsia-50/50 dark:hover:bg-fuchsia-950/50",
    focusRing: "focus-visible:ring-fuchsia-500",
    radioSelected: "border-fuchsia-500 bg-fuchsia-500",
    questionNumberBg: "bg-gradient-to-br from-fuchsia-400 to-rose-500",
  },
  "amber-orange": {
    selectedBorder: "border-amber-500",
    selectedBg: "bg-gradient-to-r from-amber-50 to-orange-50 dark:from-amber-950 dark:to-orange-950",
    hoverBorder: "hover:border-amber-300 dark:hover:border-amber-600",
    hoverBg: "hover:bg-amber-50/50 dark:hover:bg-amber-950/50",
    focusRing: "focus-visible:ring-amber-500",
    radioSelected: "border-amber-500 bg-amber-500",
    questionNumberBg: "bg-gradient-to-br from-amber-400 to-orange-500",
  },
  "rose-pink": {
    selectedBorder: "border-rose-500",
    selectedBg: "bg-gradient-to-r from-rose-50 to-pink-50 dark:from-rose-950 dark:to-pink-950",
    hoverBorder: "hover:border-rose-300 dark:hover:border-rose-600",
    hoverBg: "hover:bg-rose-50/50 dark:hover:bg-rose-950/50",
    focusRing: "focus-visible:ring-rose-500",
    radioSelected: "border-rose-500 bg-rose-500",
    questionNumberBg: "bg-gradient-to-br from-rose-400 to-pink-500",
  },
  "red": {
    selectedBorder: "border-red-500",
    selectedBg: "bg-gradient-to-r from-red-50 to-red-100 dark:from-red-950 dark:to-red-900",
    hoverBorder: "hover:border-red-300 dark:hover:border-red-600",
    hoverBg: "hover:bg-red-50/50 dark:hover:bg-red-950/50",
    focusRing: "focus-visible:ring-red-500",
    radioSelected: "border-red-500 bg-red-500",
    questionNumberBg: "bg-gradient-to-br from-red-400 to-red-600",
  },
  "violet-fuchsia": {
    selectedBorder: "border-violet-500",
    selectedBg: "bg-gradient-to-r from-violet-50 to-fuchsia-50 dark:from-violet-950 dark:to-fuchsia-950",
    hoverBorder: "hover:border-violet-300 dark:hover:border-violet-600",
    hoverBg: "hover:bg-violet-50/50 dark:hover:bg-violet-950/50",
    focusRing: "focus-visible:ring-violet-500",
    radioSelected: "border-violet-500 bg-violet-500",
    questionNumberBg: "bg-gradient-to-br from-violet-400 to-fuchsia-500",
  },
  "indigo-purple-pink": {
    selectedBorder: "border-indigo-500",
    selectedBg: "bg-gradient-to-r from-indigo-50 via-purple-50 to-pink-50 dark:from-indigo-950 dark:via-purple-950 dark:to-pink-950",
    hoverBorder: "hover:border-indigo-300 dark:hover:border-indigo-600",
    hoverBg: "hover:bg-indigo-50/50 dark:hover:bg-indigo-950/50",
    focusRing: "focus-visible:ring-indigo-500",
    radioSelected: "border-indigo-500 bg-indigo-500",
    questionNumberBg: "bg-gradient-to-br from-indigo-400 via-purple-400 to-pink-400",
  },
  "cyan-blue": {
    selectedBorder: "border-cyan-500",
    selectedBg: "bg-gradient-to-r from-cyan-50 to-blue-50 dark:from-cyan-950 dark:to-blue-950",
    hoverBorder: "hover:border-cyan-300 dark:hover:border-cyan-600",
    hoverBg: "hover:bg-cyan-50/50 dark:hover:bg-cyan-950/50",
    focusRing: "focus-visible:ring-cyan-500",
    radioSelected: "border-cyan-500 bg-cyan-500",
    questionNumberBg: "bg-gradient-to-br from-cyan-400 to-blue-500",
  },
  "cyan-blue-indigo": {
    selectedBorder: "border-cyan-500",
    selectedBg: "bg-gradient-to-r from-cyan-50 via-blue-50 to-indigo-50 dark:from-cyan-950 dark:via-blue-950 dark:to-indigo-950",
    hoverBorder: "hover:border-cyan-300 dark:hover:border-cyan-600",
    hoverBg: "hover:bg-cyan-50/50 dark:hover:bg-cyan-950/50",
    focusRing: "focus-visible:ring-cyan-500",
    radioSelected: "border-cyan-500 bg-cyan-500",
    questionNumberBg: "bg-gradient-to-br from-cyan-400 via-blue-400 to-indigo-400",
  },
  "rose-pink-purple": {
    selectedBorder: "border-rose-500",
    selectedBg: "bg-gradient-to-r from-rose-50 via-pink-50 to-purple-50 dark:from-rose-950 dark:via-pink-950 dark:to-purple-950",
    hoverBorder: "hover:border-rose-300 dark:hover:border-rose-600",
    hoverBg: "hover:bg-rose-50/50 dark:hover:bg-rose-950/50",
    focusRing: "focus-visible:ring-rose-500",
    radioSelected: "border-rose-500 bg-rose-500",
    questionNumberBg: "bg-gradient-to-br from-rose-400 via-pink-400 to-purple-400",
  },
  "orange-amber-yellow": {
    selectedBorder: "border-orange-500",
    selectedBg: "bg-gradient-to-r from-orange-50 via-amber-50 to-yellow-50 dark:from-orange-950 dark:via-amber-950 dark:to-yellow-950",
    hoverBorder: "hover:border-orange-300 dark:hover:border-orange-600",
    hoverBg: "hover:bg-orange-50/50 dark:hover:bg-orange-950/50",
    focusRing: "focus-visible:ring-orange-500",
    radioSelected: "border-orange-500 bg-orange-500",
    questionNumberBg: "bg-gradient-to-br from-orange-400 via-amber-400 to-yellow-400",
  },
  "indigo-purple": {
    selectedBorder: "border-indigo-500",
    selectedBg: "bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-950 dark:to-purple-950",
    hoverBorder: "hover:border-indigo-300 dark:hover:border-indigo-600",
    hoverBg: "hover:bg-indigo-50/50 dark:hover:bg-indigo-950/50",
    focusRing: "focus-visible:ring-indigo-500",
    radioSelected: "border-indigo-500 bg-indigo-500",
    questionNumberBg: "bg-gradient-to-br from-indigo-400 to-purple-500",
  },
  "teal-cyan": {
    selectedBorder: "border-teal-500",
    selectedBg: "bg-gradient-to-r from-teal-50 to-cyan-50 dark:from-teal-950 dark:to-cyan-950",
    hoverBorder: "hover:border-teal-300 dark:hover:border-teal-600",
    hoverBg: "hover:bg-teal-50/50 dark:hover:bg-teal-950/50",
    focusRing: "focus-visible:ring-teal-500",
    radioSelected: "border-teal-500 bg-teal-500",
    questionNumberBg: "bg-gradient-to-br from-teal-400 to-cyan-500",
  },
  "green-teal": {
    selectedBorder: "border-green-500",
    selectedBg: "bg-gradient-to-r from-green-50 to-teal-50 dark:from-green-950 dark:to-teal-950",
    hoverBorder: "hover:border-green-300 dark:hover:border-green-600",
    hoverBg: "hover:bg-green-50/50 dark:hover:bg-green-950/50",
    focusRing: "focus-visible:ring-green-500",
    radioSelected: "border-green-500 bg-green-500",
    questionNumberBg: "bg-gradient-to-br from-green-400 to-teal-500",
  },
  "yellow-amber": {
    selectedBorder: "border-yellow-500",
    selectedBg: "bg-gradient-to-r from-yellow-50 to-amber-50 dark:from-yellow-950 dark:to-amber-950",
    hoverBorder: "hover:border-yellow-300 dark:hover:border-yellow-600",
    hoverBg: "hover:bg-yellow-50/50 dark:hover:bg-yellow-950/50",
    focusRing: "focus-visible:ring-yellow-500",
    radioSelected: "border-yellow-500 bg-yellow-500",
    questionNumberBg: "bg-gradient-to-br from-yellow-400 to-amber-500",
  },
  "red-orange": {
    selectedBorder: "border-red-500",
    selectedBg: "bg-gradient-to-r from-red-50 to-orange-50 dark:from-red-950 dark:to-orange-950",
    hoverBorder: "hover:border-red-300 dark:hover:border-red-600",
    hoverBg: "hover:bg-red-50/50 dark:hover:bg-red-950/50",
    focusRing: "focus-visible:ring-red-500",
    radioSelected: "border-red-500 bg-red-500",
    questionNumberBg: "bg-gradient-to-br from-red-400 to-orange-500",
  },
  "slate-gray": {
    selectedBorder: "border-slate-500",
    selectedBg: "bg-gradient-to-r from-slate-50 to-gray-50 dark:from-slate-950 dark:to-gray-950",
    hoverBorder: "hover:border-slate-300 dark:hover:border-slate-600",
    hoverBg: "hover:bg-slate-50/50 dark:hover:bg-slate-950/50",
    focusRing: "focus-visible:ring-slate-500",
    radioSelected: "border-slate-500 bg-slate-500",
    questionNumberBg: "bg-gradient-to-br from-slate-400 to-gray-500",
  },
  "pink-purple": {
    selectedBorder: "border-pink-500",
    selectedBg: "bg-gradient-to-r from-pink-50 to-purple-50 dark:from-pink-950 dark:to-purple-950",
    hoverBorder: "hover:border-pink-300 dark:hover:border-pink-600",
    hoverBg: "hover:bg-pink-50/50 dark:hover:bg-pink-950/50",
    focusRing: "focus-visible:ring-pink-500",
    radioSelected: "border-pink-500 bg-pink-500",
    questionNumberBg: "bg-gradient-to-br from-pink-400 to-purple-500",
  },
  "emerald-teal": {
    selectedBorder: "border-emerald-500",
    selectedBg: "bg-gradient-to-r from-emerald-50 to-teal-50 dark:from-emerald-950 dark:to-teal-950",
    hoverBorder: "hover:border-emerald-300 dark:hover:border-emerald-600",
    hoverBg: "hover:bg-emerald-50/50 dark:hover:bg-emerald-950/50",
    focusRing: "focus-visible:ring-emerald-500",
    radioSelected: "border-emerald-500 bg-emerald-500",
    questionNumberBg: "bg-gradient-to-br from-emerald-400 to-teal-500",
  },
  "red-pink": {
    selectedBorder: "border-red-500",
    selectedBg: "bg-gradient-to-r from-red-50 to-pink-50 dark:from-red-950 dark:to-pink-950",
    hoverBorder: "hover:border-red-300 dark:hover:border-red-600",
    hoverBg: "hover:bg-red-50/50 dark:hover:bg-red-950/50",
    focusRing: "focus-visible:ring-red-500",
    radioSelected: "border-red-500 bg-red-500",
    questionNumberBg: "bg-gradient-to-br from-red-400 to-pink-500",
  },
}

export function getQuizColorScheme(schemeName: string): QuizColorClasses {
  return quizColorSchemes[schemeName] || quizColorSchemes["blue-green"]
}

